// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eovettptettckkpdlxxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvdmV0dHB0ZXR0Y2trcGRseHh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2OTM3NTEsImV4cCI6MjA3MjI2OTc1MX0.5n-wt8HuFDxKZGH7LcO4UCM11g_TTwt2M4tNw2tRFz4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});