// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Prefer environment variables; fall back to empty string if not defined.
// For Vite, variables must be prefixed with VITE_ to be exposed to the client.
const SUPABASE_URL = (import.meta.env.VITE_SUPABASE_URL || '').trim();
const SUPABASE_PUBLISHABLE_KEY = (import.meta.env.VITE_SUPABASE_ANON_KEY || '').trim();

const missingEnv = !SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY;
if (missingEnv) {
  console.error("[Supabase] Variáveis de ambiente ausentes. Defina VITE_SUPABASE_URL e VITE_SUPABASE_ANON_KEY.");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Evita quebrar totalmente a aplicação em produção exibindo telas vazias; funções que chamarem
// supabase com credenciais vazias irão falhar nas requisições, porém a UI ainda renderiza.
export const supabase = !missingEnv
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: typeof window !== 'undefined' ? localStorage : undefined,
        persistSession: true,
        autoRefreshToken: true,
      }
    })
  : createClient<Database>('https://example.supabase.co', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.placeholder', {
      auth: { persistSession: false }
    });